#------------------ IDENTIFIER STATE AND LABEL ----------------#
START_STATE = 0
STATE1 = 1
STATE2 = 2
STATE3 = 3
STATE4 = 4
END_STATE = 5
N_ = -1

DOLLAR = 0
AT = 1
LETTER = 2
DIGIT = 3

#------------------ INTEGER STATE AND LABEL ----------------#
INT_START_STATE = 0
INT_STATE1 = 1
INT_END_STATE2 = 2
INT_END_STATE3 = 3
INT_END_STATE4 = 4
INT_END_STATE5 = 5

ADD_MINUS = 0
ZERO = 1
ONE_TO_SEVEN = 2
EIGHT_TO_NINE = 3

#------------------ FLOAT STATE AND LABEL ----------------#
FLOAT_START_STATE = 0
FLOAT_STATE1 = 1
FLOAT_STATE2 = 2
FLOAT_STATE3 = 3
FLOAT_STATE4 = 4
FLOAT_END_STATE = 5

FONE_TO_NINE = 2
FDOT = 3

